import streamlit as st

def disclaimer():
    st.write("""
                ### AI is just statistics, it can't really think and thus can't be trusted to tell the truth
                This site may produce inaccurate information - Generative AI Is just fancy statistics. So in a clever way all the words you see generated are just the most probable next words. Without basing them in any facts. Always use your own judgement when reading the results from this AI.  """)
    st.write("""
    ### Privacy Disclaimer

    **Your Choices Matter:**
    This app allows you to upload and preview personal documents. Be mindful of the information you choose to share, consider them public until you hit the delete button. Only upload and interact with documents that you are comfortable sharing, and always consider the privacy implications.

    **Sensitive Information:**
    Avoid uploading sensitive or confidential information. We provide a demo dataset to play around with. Understand that the app processes information for display purposes only Also be aware that snippits of text might be sent to OpenAI to be processed by the Large Language model to provide an answer back in the prompt.

    **Your Responsibility:**
    You are responsible for the documents you choose to upload. Ensure you comply with privacy laws and regulations. Be cautious about sharing personally identifiable information. And use the demo dataset for sensitive stuff.  

    **Security Measures:**
    While we take measures to ensure the security of the app, there is always a risk associated with online interactions. Use the app in a secure and private environment.

    **Questions or Concerns:**
    If you have questions or concerns about privacy, feel free to reach out to us.

    """)
    st.write("""
    ### No Responsibility Disclaimer

    **Use at Your Own Risk:**
    This app is provided as-is, and we do not guarantee the accuracy or completeness of the information it produces. The app generates answers based on statistical data and may not always provide factual information.

    **Limitation of Liability:**
    We disclaim any responsibility for the consequences of using this app. The information provided is for informational purposes only, and we do not accept any liability for actions taken based on the app's outputs.

    **User Responsibility:**
    You, as the user, are solely responsible for the choices you make based on the information generated by the app. Verify critical information independently before making decisions.

    **No Warranty:**
    We make no warranties, expressed or implied, regarding the app's functionality, accuracy, or fitness for a particular purpose.

    **Changes and Updates:**
    We may update or modify the app without notice, and we are not obligated to provide support or updates.

    **Questions or Concerns:**
    If you have any questions or concerns, please contact us.

    """)
