import streamlit as st

st.write("# About DocBot Fusion 👋")
st.write("**DocBot Fusion** is an innovative web application that combines the conversational prowess of ChatGPT with advanced document analysis. Created by Peter van Doorn, this app processes uploaded documents, extracting insights and generating contextually relevant responses.")
st.write("## Key Features:")
st.write("- Seamless Integration: The app seamlessly integrates ChatGPT's conversational abilities with document analysis.")
st.write("- Document Processing: Upload documents for extraction of valuable insights and contextually relevant responses.")
st.write("- Conversational Retrieval Chain: Powered by the sophisticated Conversational Retrieval Chain, orchestrating user queries with the ChatOpenAI model.")
st.write("- Persistence: The app enables model reuse for repeated queries on the same data, optimizing performance.")
st.write("## Usage:")
st.write("1. **Chat Interface:** Engage in dynamic conversations by inputting questions or selecting predefined queries with intuitive buttons.")
st.write("2. **Document Analysis:** Leverage the app to process uploaded documents for insightful information retrieval.")
st.write("## Disclaimer:")
st.write("**Accuracy Warning:** The app's answers are probabilistic and based on statistical patterns. Users are advised to critically evaluate results.")
st.write("## About the Creator:")
st.write("**Peter van Doorn** developed and maintains DocBot Fusion.")
st.write("## Code on GitHub:")
st.write("Explore and utilize the app's code on [GitHub](https://github.com/two-trick-pony-NL/gpt-document-search).")
st.write("---")
st.write("*Note: This page was generated using Streamlit and is designed to offer an interactive and informative experience.*")
